import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  return (
    <div data-theme="garden" className="h-screen ">
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/auth/signup">
        <a className="btn">signup</a>
      </Link>
      <Link href="/auth/signin">
        <a className="btn">signin</a>
      </Link>
      <a className="btn" onClick={()=>{
        sessionStorage.clear()
      }}>logout</a>
    </div>
  );
};

export default Home;
